# Generated by Django 5.2.1 on 2025-05-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasoEnsamblaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(unique=True)),
                ('nombre_pieza', models.CharField(max_length=50)),
                ('led_asociado', models.PositiveIntegerField()),
                ('boton_correcto', models.PositiveIntegerField()),
            ],
        ),
    ]
